# Generated by Django 2.2.3 on 2019-08-20 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qqname', models.CharField(max_length=200)),
                ('qq_date', models.CharField(max_length=10)),
                ('qq_desc', models.TextField()),
                ('qq_que', models.BooleanField()),
                ('qq_can', models.BooleanField()),
                ('qq_logo', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
